### ISSUE TITLE
Version 1.2 is not available on Modrinth

### ISSUE THREAD

**Issue by Poopooracoocoo** [cleannrooster/extraspellattributes#1]
Just letting you know that [Extra RPG Attributes 1.2](https://www.curseforge.com/minecraft/mc-mods/extra-spell-attributes/files/5254342) is not available on Modrinth.

And just a heads up that there's no link to this issue tracker or the source code on the [Modrinth page](https://modrinth.com/mod/extra-rpg-attributes).

Thanks!! :)

**Comment by cleannrooster** [comment]
Should be dealt with!

**Comment by Poopooracoocoo** [comment]
Thanks! I'd also appreciate if you could add links to the source code and issue tracker to your Modrinth page!
