### ISSUE TITLE
Tooltip rendering crash for various items in multiplayer

### ISSUE THREAD

**Issue by ZarTaen** [cleannrooster/extraspellattributes#2]
Honestly, Im not sure that the issue originates in this mod specifically. Reason I am posting this here is that is where one of the traces seems to point towards. Those traces may just be a symptom however. We of course play with Spellblades and Such. 

Observations: 
After defeating Magus in the Glass Ocean a couple of times on our server, all of a sudden I had instant crashes for various Spellblade, Wizards RPG and Paladins & Priests items the moment I am trying to hover over them. This includes some items in EMI directly. Spellblade spellbooks (but apparently only the instanced ones with spells attached in the inventory), items like the crystal cutlass in my hand as well as inside EMI, items with oil applied, the Paladin claymores or the Wizards and Priest staffs. Armor is specifically NOT impacted. 

These crashes do **not happen in singleplayer**, only on that server right now. They may have started when I obtained Ashes of the Stars and Crystallised Omniscience, but I think thats coincidence. The server log shows no issues. 

One example of a log with crash is attached here: 
[Crashlog.MC.txt](https://github.com/user-attachments/files/15749484/Crashlog.MC.txt)

The log shows how, when connected to the server, EMI struggles getting some recipes related to the crashing items, so I guess the server does not respond correctly for some items anymore. This is after around 30 hours+ of gameplay without issues. 

If the issue is related to another mod after all, I will happily post the issue there.

Thanks in advance.

**Comment by cleannrooster** [comment]
I will be uploading a fix for this soon, within the next 10 minutes. Due to
the nature of the crash being clientside you should be able to test it by
just replacing your client's extraspellattributes without replacing the
server's.

**Comment by ZarTaen** [comment]
Yes, the fix indeed fixed the crashes I have had, thanks a lot for the quick response :D
