### ISSUE TITLE
Math error in Battle Rouse enchantment.

### ISSUE THREAD

**Issue by thermad** [cleannrooster/extraspellattributes#5]
In line 48 of LivingEntityRecoupMixin.java:
double total = amount*(0.01*((living.getAttributeValue(RECOUP)-100)+ ExtraRPGEnchantment.getEnchantmentLevelEquipmentSum(BATTLEROUSE,living)*config.battlerouseenchant));

The enchantment sum is within the parenthesis and getting multiplied by 0.01 to factor it as a percent, but the value saved in the config file already is representing a percent. As a result, the enchantment only ends up healing 0.04% per level, instead of 4% per level.

**Comment by cleannrooster** [comment]
Thank you for bringing this up.
I will make it so that the 0.01 only applies to the attribute.

**Comment by cleannrooster** [comment]
Fixed
