### ISSUE TITLE
Regeneration that goes beyond the law of the world

### ISSUE THREAD

**Issue by Zaaees** [cleannrooster/extraspellattributes#6]
I noticed that the mod's regeneration was not affected by the rule that allows automatic regeneration to be disabled. Is there a way around this, to cancel the mod regeneration?

**Comment by cleannrooster** [comment]
My interpretation of automatic regeneration is that it is considered "natural" regeneration, while regeneration from other sources are unnatural and therefore not affected by the gamerule.

Still, I can add a gamerule to cancel the mod regeneration - if that is something that you would like.
